In [13]:
# Question 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(np.greater(array1,array2))
print(np.greater_equal(array1,array2))
print(np.less(array1,array2))
print(np.less_equal(array1,array2))

[False False False]
[False False False]
[ True  True  True]
[ True  True  True]


In [14]:
# Question 2: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

array=np.zeros(10)
print(array)
array=np.ones(10)
print(array)
array=np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [24]:
# Question 3: Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

array1=np.array([[1,2,3],[4,5,6]])
print(np.sum(array1))
print(np.sum(array1,axis=0))
print(np.sum(array1,axis=1))

21
[5 7 9]
[ 6 15]


In [27]:
# Question 4: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

print(np.add(55,56))
print(np.multiply(55,56))
print(np.divide(55,56))

111
3080
0.9821428571428571


In [30]:
# Question 5: Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

print(np.sin(np.array((1,2,3))*np.pi/180))
print(np.cos(np.array((1,2,3))*np.pi/180))
print(np.tan(np.array((1,2,3))*np.pi/180))

[0.01745241 0.0348995  0.05233596]
[0.9998477  0.99939083 0.99862953]
[0.01745506 0.03492077 0.05240778]


In [1]:
!pip install pandas

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 20.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [4]:
# Question 6: Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

import numpy as np
import pandas as pd
exam_data  = {'name': ['Tanushree', 'Tina', 'Mani', 'Mahasweta', 'Srinivas','Jonathan'],
        'score': [88, 91, 33.5, 77, np.nan, 46],
        'attempts': [1, 1, 3, 1, 2, 3],
        'qualify': ['yes', 'yes', 'no', 'yes', 'no', 'yes']}
labels = ['1', '2', '3', '4', '5', '6']
f = pd.DataFrame(exam_data , index=labels)
print(f)

        name  score  attempts qualify
1  Tanushree   88.0         1     yes
2       Tina   91.0         1     yes
3       Mani   33.5         3      no
4  Mahasweta   77.0         1     yes
5   Srinivas    NaN         2      no
6   Jonathan   46.0         3     yes


In [11]:
# Question 7: Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

exam_data  = {'name': ['Tanushree', 'Tina', 'Mani', 'Mahasweta', 'Srinivas','Jonathan'],
        'score': [88, 91, 33.5, 77, np.nan, 46],
        'attempts': [1, 1, 3, 1, 2, 3],
        'qualify': ['yes', 'yes', 'no', 'yes', 'no', 'yes']}
labels = ['1', '2', '3', '4', '5', '6']
f = pd.DataFrame(exam_data , index=labels)
print(f[['name','score']])

        name  score
1  Tanushree   88.0
2       Tina   91.0
3       Mani   33.5
4  Mahasweta   77.0
5   Srinivas    NaN
6   Jonathan   46.0


In [7]:
# Question 8: Write a Pandas program to join the two given dataframes along rows and assign all data

exam_data1  = {'name': ['Tanushree', 'Tina', 'Mani', 'Mahasweta', 'Srinivas','Jonathan'],
        'score': [88, 91, 33.5, 77, np.nan, 46],
        'attempts': [1, 1, 3, 1, 2, 3],
        'qualify': ['yes', 'yes', 'no', 'yes', 'no', 'yes']}
exam_data2  = {'name': ['Billy', 'Carina', 'Justin', 'Tim', 'Kishore','Sai'],
        'score': [78, 87, 56.7, 70, 63, 54],
        'attempts': [1, 1, 2, 1, 1, 3],
        'qualify': ['yes', 'yes', 'yes', 'yes', 'yes', 'yes']}

print(exam_data1)
print(exam_data2)
totaldata=pd.concat([exam_data1,exam_data2])
prrint(totaldata)

{'name': ['Tanushree', 'Tina', 'Mani', 'Mahasweta', 'Srinivas', 'Jonathan'], 'score': [88, 91, 33.5, 77, nan, 46], 'attempts': [1, 1, 3, 1, 2, 3], 'qualify': ['yes', 'yes', 'no', 'yes', 'no', 'yes']}
{'name': ['Billy', 'Carina', 'Justin', 'Tim', 'Kishore', 'Sai'], 'score': [78, 87, 56.7, 70, 63, 54], 'attempts': [1, 1, 2, 1, 1, 3], 'qualify': ['yes', 'yes', 'yes', 'yes', 'yes', 'yes']}


TypeError: cannot concatenate object of type "<class 'dict'>"; only pd.Series, pd.DataFrame, and pd.Panel (deprecated) objs are valid

In [18]:
# Question 9: Write a Pandas program to detect missing values of a given DataFrame. Display True or False

exam_data1  = {'name': ['Tanushree', 'Tina', 'Mani', 'Mahasweta', 'Srinivas','Jonathan'],
        'score': [88, 91, 33.5, 77, np.nan, 46],
        'attempts': [1, 1, 3, 1, 2, 3],
        'qualify': ['yes', 'yes', 'no', 'yes', 'no', 'yes']}
f = pd.DataFrame(exam_data)
print(f)
print(f.isna())

        name  score  attempts qualify
0  Tanushree   88.0         1     yes
1       Tina   91.0         1     yes
2       Mani   33.5         3      no
3  Mahasweta   77.0         1     yes
4   Srinivas    NaN         2      no
5   Jonathan   46.0         3     yes
    name  score  attempts  qualify
0  False  False     False    False
1  False  False     False    False
2  False  False     False    False
3  False  False     False    False
4  False   True     False    False
5  False  False     False    False


In [20]:
# Question 10: Write a Pandas program to create and display a one-dimensional array-like object containing an array of data.

array=pd.Series([1,2,3,4,5,6])
print(array)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
